### PR TITLE
Don't error out on 'Africa/Abidjan' timezone [gyst]

### LINKED ISSUE #393: ical export breaks
I guess this is because 'Africa/Abidjan' is perhaps the first timezone?

```
  Module plone.app.event.ical.exporter, line 408, in __call__
  Module plone.app.event.ical.exporter, line 404, in get_ical_string
  Module zope.component.hooks, line 144, in adapter_hook
  Module plone.app.event.ical.exporter, line 177, in calendar_from_container
  Module plone.app.event.ical.exporter, line 65, in construct_icalendar
  Module plone.app.event.ical.exporter, line 144, in add_to_zones_map
  Module plone.app.event.ical.exporter, line 140, in localize
  Module pytz.tzinfo, line 204, in fromutc
OverflowError: date value out of range
```

```
(Pdb) tz
<DstTzInfo 'Africa/Abidjan' LMT-1 day, 23:44:00 STD>
(Pdb) prev_transition
datetime.datetime(1, 1, 1, 0, 0)
(Pdb) tzmap
{}
(Pdb) tzid
'Africa/Abidjan'
(Pdb) dt
datetime.datetime(2015, 2, 5, 0, 0, tzinfo=<DstTzInfo 'Africa/Abidjan' GMT0:00:00 STD>)

(Pdb) datetime.min
datetime.datetime(1, 1, 1, 0, 0)
(Pdb) prev_transition
datetime.datetime(1, 1, 1, 0, 0)
(Pdb) prev_transition is datetime.min
True
(Pdb) prev_transition is null
False
```

Fix forthcoming

### PR DESCRIPTION
**Pull request by gyst**
Fixes #393 by not using our own `null` datetime, which was equal but not identical to `datetime.min`.

The test provided throws an OverflowError without the patch provided.

### CODE REVIEW

**Comment by gyst** [comment]
Please note that running tests locally gives two errors I also get when running tests against `master`.

**Comment by gyst** [comment]
@jenkins-plone-org please run jobs

**Comment by davisagli** [comment]
@gyst I tried this in a Plone site with the site timezone set to Africa/Abidjan. This change avoids the OverflowError, but I got a different error instead.

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 181, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 391, in publish_module
  Module ZPublisher.WSGIPublisher, line 285, in publish
  Module ZPublisher.mapply, line 98, in mapply
  Module ZPublisher.WSGIPublisher, line 68, in call_object
  Module plone.app.event.ical.exporter, line 407, in __call__
  Module plone.app.event.ical.exporter, line 403, in get_ical_string
  Module zope.component.hooks, line 144, in adapter_hook
  Module plone.app.event.ical.exporter, line 165, in calendar_from_event
  Module plone.app.event.ical.exporter, line 82, in construct_icalendar
  Module icalendar.cal, line 194, in add
  Module icalendar.cal, line 145, in _encode
  Module icalendar.prop, line 852, in __init__
ValueError: Offset value MUST be a timedelta instance
```

**Comment by gyst** [comment]
This fix is for an event with the timezone set to Africa/Abidjan. I did not think about setting the site timezone. This looks like potentially a separate (though similar) bug?

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
I think @davisagli found a different bug. I am fine to merge this one if all is green here and you create a new issue with above findings.

**Pull request merged**
