### PR TITLE
Point to documentation

### PR DESCRIPTION
**Pull request by gforcada**
Fixes https://github.com/plone/plone.app.event/issues/179

@svx do we host that documentation somewhere on docs.plone.org? Should I open a ticket for it? @thet any reason not to move the docs to docs.plone.org?

### CODE REVIEW

**Comment by thet** [comment]
@gforcada so, no docs in packages, all in docs.plone.org?

**Comment by svx** [comment]
@gforcada @thet please do add documentation into the package repo, if possible in /docs, we will just fetch them and include them into the docs.plone.org.
With this is will make it much easier to keep the docs up to date.
Thanks !

**Comment by gforcada** [comment]
@thet no, the docs stay in p.a.event, but they are rendered on docs.plone.org instead of readthedocs, so we have everything in a single place.

If we do that, then this PR needs to be changed. But first a PR needs to be sent to https://github.com/plone/documentation to add it. Am I right @svx? What's the process to incorporate new docs on docs.plone.org?

**Comment by svx** [comment]
@gforcada. @thet  for the moment the only thing we need to know is:

- loaction of the docs in plone.app.event
- where to include them on docs.plone.org
- include them for version [version of plone]

For this you do not have to make a pull request to the docs, because we have to include them in papyrus, you could/should make a pr for papyrus :)

I will a writeup about all of this soon, I am quite swamped with daily work for the next couple of days ...

**Comment by pbauer** [comment]
@svx here are the things you need to know to include them in docs.plone.org:

- the docs are here: https://github.com/plone/plone.app.event/tree/master/docs
- on docs.plone.org they should be after http://docs.plone.org/develop/index.html#plone-app-contentlisting
- include them for 4 and 5

**Comment by jensens** [comment]
close here, head overt to doc team to include in plone/papyrus#67

**Comment by jensens** [comment]
merge. its not that easy to include pa.event docs into papyrus because it uses a bunch a sphinx plugins.

**Pull request merged**
