### PR TITLE
When trying to access an occurrence in the future, do not raise StopIteration

### PR DESCRIPTION
**Pull request by frapell**

### CODE REVIEW

**Comment by frapell** [comment]
@thet When you have a sec, please review this :)

**Comment by thet** [comment]
Looks good!

Do you have the use case of accessing occurrences in the far future?
We have a ``plone.event.recurrence.MAXCOUNT`` constant, which is set to 1000 occurrences. After that, no more occurrences are indexed. That's a bit of a drawback we had to made for non-lazy indexers, where all possible occurrences are indexed at modification/creation time of the object. 
@regebro did a lazy indexer, which indexes on first access, which could be an alternative - but it's not a drop-in replacement: https://github.com/collective/plone.app.eventindex

**Comment by regebro** [comment]
It's *almost* drop-in, and really cool, but nobody ended up using it, so
it's practically unmmaintaned. It's also not lazy, but smart. ;-)

**Comment by frapell** [comment]
@thet No, not really... in our case we have a site where bots crawl it and keep hitting these non-existing occurrences and flooding the monitoring software with these StopIteration exceptions. I think at one point, editors changed the recurrence rules for a bunch of events, so crawlers keep trying to access the no longer existing ones.

I wasn't aware of the MAXCOUNT limit... I don't think we ever come close to it, but is a good thing to keep in mind.

**Comment by thet** [comment]
@regebro smart for sure :)

once someone will come across the usecase to integrate plone.app.eventindex into plone.app.event...!

**Pull request merged**
