### PR TITLE
Fix date conversion when collection context has start/end date queries

### PR DESCRIPTION
**Pull request by petschki**
fixes https://github.com/plone/Products.CMFPlone/issues/3959

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
I like small fixes. :-)
Tested and it works for me.

**Comment by petschki** [comment]
especially when the testing code is twice as long as the fix itself 😁

**Pull request merged**
