### PR TITLE
Fix bug when an event is in creation and has not yet uid.

### PR DESCRIPTION
**Pull request by bsuttor**
Some behavior notify IObjectModifiedEvent, and event is not created when this notify is called, 
So event UUID has not yet been assigned and we have a TypeError.

Now we check if UUID is assigned

### CODE REVIEW

**Comment by bsuttor** [comment]
I don't understand this error on Jenkins :

    bin/jenkins-alltests: No such file or directory

I tried to rebuild job, but Jenkins says `An error occured. Please try again.`

Is there someone which could help me on this ?

**Comment by bsuttor** [comment]
Can I merge it ? It's a very little change, I just change 

    uid = IUUID(obj)

by 

    uid = IUUID(obj, None)
        if uid:

**Comment by bsuttor** [comment]
@mauritsvanrees could you please review it ?

**Comment by mauritsvanrees** [comment]
LGTM.

I have fired up Jenkins once more, let's see if it recovers.

**Comment by mauritsvanrees** [comment]
Jenkins still fails. Ah, when you look closely, you will see this in the console output:

> mr.developer: The package 'plone.app.event' from auto-checkout has no source information.

A source definition *is* in `ecosystem.cfg`, but that is not loaded during tests.

Well, the change looks fine. I will merge.

**Comment by mauritsvanrees** [comment]
I have released 1.1.7 with this fix. Thanks!

**Comment by bsuttor** [comment]
Thanks a lot for merging !

**Pull request merged**
