### PR TITLE
"removing dependency on p.a.contenttypes" second trial (Revert "Revert #195)

### PR DESCRIPTION
**Pull request by jensens**
Reverts plone/plone.app.event#196

Original the same as #195

### CODE REVIEW

**Comment by jensens** [comment]
testing here again http://jenkins.plone.org/job/pull-request-5.0/112/

**Comment by jensens** [comment]
@garbas @thet I have have no idea what it was that broke jenkins (see above PR testing), but it did, please have a look at it, then we try again.

**Comment by jensens** [comment]
http://jenkins.plone.org/job/pull-request-5.0/130/

**Comment by thet** [comment]
Interesting, which side effects a wrong import can cause...

**Pull request merged**
