### PR TITLE
Unified event_listing style with plonetheme.barceloneta styles and added svg icons.

### PR DESCRIPTION
**Pull request by agitator**

### CODE REVIEW

**Comment by jensens** [comment]
@thet may you look at it? does master targets plone 5 only?

**Comment by thet** [comment]
@agitator does these changes target plone 5 only?

**Comment by thet** [comment]
in a newly created plone 5 site with the ``plone5-event-view`` branch in place, everything looks great!

but first i have created a plone 5 site without the plone.app.event ``plone5-event-view`` branch included, created some events. then i switched to the ``plone5-event-view`` branch. it looks like so:

plone app event-issue-194

in http://localhost:8080/Plone/@@resourceregistry-controlpanel i don't have an option to recompile the plone-legacy bundle. ./bin/plone-compile-resources also doesn't help.

there is some sort of upgrade step missing...

**Comment by pbauer** [comment]
I think this should be Plone 5 only

**Comment by agitator** [comment]
yes, plone 5 targeted, thought that's what the master is for ;-)
@thet ping me

**Comment by pbauer** [comment]
@thet after switching css-develop mode for plone-legacy on and off again the new styles in ``++resource++plone.app.event/event.css`` got picked up nicely. 
Should the css maybe move to plonetheme.barceloneta? The method to switch view-modes could be improved to use the contentload-pattern (ajax). Still I really like it.

**Comment by thet** [comment]
I'm on vacation and cannot contribute.

**Pull request merged**
