### PR TITLE
Resolve deprecation warning for getDefaultPage.

### PR DESCRIPTION
**Pull request by fulv**
Fixes plone/Products.CMFPlone#1019.

### CODE REVIEW

**Comment by jensens** [comment]
label pr testing - but where is the test? 
here I added one http://jenkins.plone.org/job/pull-request-5.0/372/

**Comment by jensens** [comment]
http://jenkins.plone.org/job/pull-request-5.0/374/

**Comment by fulv** [comment]
Sorry!  Where do I go for a legend of all the labels?

**Comment by jensens** [comment]
Sorry, documentation is work in progress, postponed in order to get 5.0 out of the door. I also planned to harmonize all the labels in github plone organisazion. See my posting here: https://community.plone.org/t/better-labels-for-all-core-packages/736

You can add test runs for pull requests yourself by login in to http://jenkins.plone.org/job/pull-request-5.0/ with your github account and then choose "build with parameters" and fill in the URL of the pull request. In this case this would be "https://github.com/plone/plone.app.event/pull/200". Then paste the url of the newly started job here.

**Comment by fulv** [comment]
Coo, thanks!

**Pull request merged**
