### PR TITLE
Don't purge types when adding event types

### PR DESCRIPTION
**Pull request by tomgross**

### CODE REVIEW

**Comment by tomgross** [comment]
This should fix https://github.com/plone/Products.CMFPlone/issues/635

**Comment by tomgross** [comment]
http://jenkins.plone.org/job/pull-request-5.0/36/

**Comment by tomgross** [comment]
All green

**Comment by thet** [comment]
Does it currently really purge the FTI profiles? I'm wondering - if so, I have to recheck all my Plone projects...

**Comment by tomgross** [comment]
At least it gives an error when installing AT content.

**Comment by thet** [comment]
can it be, that this is related to plone.app.event master targeting plone.app.dexterity only? maybe, you are not using plone.app.dexterity and have conflicting collection and folder types, defined in archetypes?
can i easily reproduce the problem?

**Comment by mauritsvanrees** [comment]
Surely the current purge=False in the view_methods is enough?
I do not see view_methods or other properties disappearing when I reapply the plone.app.event profile.

Oh, but I see something else that may be the cause here. We have profiles/defaults/types.xml which says:

```
<?xml version="1.0" encoding="UTF-8"?>
<object name="portal_types" meta_type="Plone Types Tool">
  <object name="Plone Site" meta_type="Factory-based Type Information with dynamic views"/>
  <object name="Folder"     meta_type="Dexterity FTI"/>
  <object name="Collection" meta_type="Dexterity FTI"/>
</object>
```

I guess this means that if the Folder type is from Archetypes and you install plone.app.event that it completely replaces the Folder type with an almost empty dexterity type.

As far as I have seen, it is not needed at all to have a `types.xml` in this case. This is only needed when you add your own new types.  For changing existing types, the files in the `types` folder are enough.

**Comment by thet** [comment]
@mauritsvanrees good point! @tomgross could you update your PR and only remove the types.xml?

**Comment by jensens** [comment]
the ``purge=False`` are already in master. so i think this one is obsolete.

**Pull request closed without merging**
