### PR TITLE
Add start and end getters for dx EventAccessor

### PR DESCRIPTION
**Pull request by bsuttor**
This PR fix this issues https://github.com/plone/plone.app.contenttypes/issues/285
The way to get occurrence/event change in 1.2.x versions, so it's only fix 1.1.x issue.

### CODE REVIEW

**Comment by thet** [comment]
Tnx for the fix! I'll review it ASAP - so beginning of next week. If not, ping me again, please.
I have also check, if this has any side effects, implications and if it applies to other plone.app.event branches also (1.2.x and master).

**Comment by bsuttor** [comment]
Ping @thet ;-)

**Comment by thet** [comment]
I think this should be fixed differently. Your pull-request allows start and end to have no timezone information, which is wrong and would lead to other problems.
My first guess is, that the migration does not fire an EventCreated or EventModified event and the data_postprocessing handler (which was necessary in plone.app.event < 2) can't get active.

**Comment by thet** [comment]
@bsuttor any update on this? looks like it's related to https://github.com/plone/plone.app.contenttypes/issues/279#issuecomment-154435357

**Comment by bsuttor** [comment]
It's a migration problem. 
No time-zone are set to event during migration even if you set a default time-zone.
So you can close de PR without merging it.

**Comment by thet** [comment]
would be great to have that fixed in plone.app.contenttypes....

**Pull request closed without merging**
