### PR TITLE
Remove cyclic dependency with Products.CMFPlone.

### LINKED ISSUE #341: Cyclic dependency with Products.CMFPlone
Ref: plone/Products.CMFPlone#3304

### PR DESCRIPTION
**Pull request by ericof**
Fixes #341

### CODE REVIEW

**Comment by ericof** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — CHANGES_REQUESTED** [review]
Can you do it the other way around? So keep plone.app.event depending on plone.app.portlets, but break the dependency cycle in plone.app.portlets.

Why? They are depending on each other for the calendar portlet. Both packages have a version of this portlet. But `plone/app/portlets/portlets/calendar.py` is nowhere used. It is not registered in zcml. So this is likely only for backwards compatibility, to avoid a Broken object.

**Comment by mauritsvanrees** [comment]
I have aborted the Jenkins jobs.

**Comment by ericof** [comment]
@mauritsvanrees Perfect, doing it

**Pull request closed without merging**
