### PR TITLE
Fixed possible XSS attack in location field. [master]

### PR DESCRIPTION
**Pull request by mauritsvanrees**

### CODE REVIEW

**Comment by thet** [comment]
Oh.
The ``structure`` modifier was meant as a way to properly display html content via addons. E.g. collective.venue overloads the location behavior, stores a reference in the location field and displays links to venue objects.
Are all fields using ``structure`` exposed to XSS attacks?

**Comment by mauritsvanrees** [comment]
Yes.  Well, when the input would be sanitised on the backend then it would be fine. But that does not always happen.

**Comment by mauritsvanrees** [comment]
I felt free to remove it here because the `get_location` method was already removed on master, making the `structure` expression unneeded. In the changelog you already said people should override the template if they wanted special handling of the location.
BTW, this is part of a few changes by the Plone security team, which were deemed to be not serious enough for a full hotfix. We will make an announcement about this later.

**Comment by thet** [comment]
OK - it was somehow a hack anyways. I'll revisit collective.venue today and see how I can handle it differently.

**Pull request merged**
