### PR TITLE
index1445-calendarwidget

### PR DESCRIPTION
**Pull request by janga1997**

### CODE REVIEW

**Comment by janga1997** [comment]
I sent a mail with the contributors agreement pdf file to assignments@plone.org, how long does it take to process?

**Comment by thet** [comment]
I don't know, but shouldn't take too long.
/cc @ableeb

**Comment by ableeb** [comment]
@janga1997 Welcome! Your Contributors Agreement has been processed
/cc @thet

**Comment by janga1997** [comment]
@ableeb Should I have received the invitation by now on github? Because if so, I didn't receive one.

**Comment by ableeb** [comment]
Yes you should have received the invitation via email. You should be able to accept it at https://github.com/plone <https://github.com/plone>. Let me know if you don’t see it there and I’ll resend it.

**Comment by janga1997** [comment]
@ableeb thanks. I got it.

**Comment by prakharjoshi** [comment]
@janga1997  Please assign someone or wait for someone to merge the PR. There may be end cases where PR needs changes even if travis is happy.

**Comment by janga1997** [comment]
@prakharjoshi I am sorry for mistake. Can I revert it through the Revert button?

**Comment by prakharjoshi** [comment]
@janga1997  Also before merging the code please run a jenkins job and test it first :)

**Comment by janga1997** [comment]
@prakharjoshi Rookie's mistake. So,do I have to create another pull request after testing it?

**Comment by prakharjoshi** [comment]
@jensens  Will help you out with that. He will create a jenkins job for you.

**Comment by jensens** [comment]
You can always start a Jenkins job to test that your pull request (PR) does not break anything. 

To do so:
- go to http://jenkins.plone.org
- log in with your Github user
- click on the [Pull Request 5.1 job](http://jenkins.plone.org/job/pull-request-5.1/)
- click on the huge menu link ["Build with Parameters"](http://jenkins.plone.org/job/pull-request-5.1/build?delay=0sec)
- paste the pull request URL into the text field (if multiple pull requests need to be combined in one run, then one PR URL per line)
- click on **Build**

Jenkins reports back to the pull request(s) on Github in the status box at the bottom.

In Plone we value a lot our testing suite, so we usually never merge pull requests if they have not been tested by Jenkins first.

**Comment by jensens** [comment]
@agitator since you are a) in UI/UX team and b) did recently some work on the calendar widget: may you please review?

**Comment by janga1997** [comment]
@agitator I started the test a few minutes ago. Thanks for the links.

**Comment by janga1997** [comment]
@jenses 


The test showed no errors,what should I do next?

**Comment by pigeonflight** [comment]
Wait for someone to review it, generally you want someone else to do the merge after passing tests and review.

**Pull request merged**
