### PR TITLE
Use src layout to fix editable install with pip

### PR DESCRIPTION
**Pull request by mauritsvanrees**
See https://github.com/plone/meta/issues/172

This uses a clone of the `plone.app.uuid` [`src-layout` branch](https://github.com/plone/plone.app.uuid/pull/24) to test that two such packages together work.  Seems fine locally.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
Replaced by PR #385, although the current PR would still be fine on top of that.

**Comment by thet** [comment]
This would mess up the GitHub history or at least make it more difficult to browse through the history.
But if it fixes problems playing together with standard tools, I'm fine with that. We probably would want do that for all Plone packages and within an coordinated effort.

**Comment by jensens** [comment]
I think this one is outdated. @mauritsvanrees ok to close?

**Comment by mauritsvanrees** [comment]
Yes, we can close.  This is something to pick up again for Plone 7 when moving to native namespaces.

**Pull request closed without merging**
